<?php

namespace AppBundle\Repository;

/**
 * InBoxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InBoxRepository extends \Doctrine\ORM\EntityRepository
{
}
