<?php

namespace AppBundle\Repository;

/**
 * NewCarousselRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewCarousselRepository extends \Doctrine\ORM\EntityRepository
{
}
