<?php

namespace AppBundle\Repository;

/**
 * NewsLetterFormulaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsLetterFormulaireRepository extends \Doctrine\ORM\EntityRepository
{
}
