<?php

namespace AppBundle\Repository;

/**
 * PromosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromosRepository extends \Doctrine\ORM\EntityRepository
{
}
